application: ppldict
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheet
  static_dir: stylesheet

- url: /.*
  script: home.py

#- url: /(.*\.(gif|png|jpg))
#  static_files: static/\1
#  upload: static/(.*\.(gif|png|jpg))

- url: /admin/.*
  script: admin.py
  login: admin